version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  build-and-test:
    docker:
      - image: cimg/node:19.0.0

    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: npm install
      - run: npm run build
      - run: npm run build:test

workflows:
  build:
    jobs:
      - build-and-test
